### ISSUE TITLE
Can you PLEASE use rule34.paheal.net in similar project?

### ISSUE THREAD

**Issue by MajoraMajora** [LordOfPolls/Rule34-Downloader#10]
it's basically the main rule34

**Comment by LordOfPolls** [comment]
I'll look into adding it

**Comment by MajoraMajora** [comment]
Thanks. If youre not super specific in the xxx version you get nothing but furry porn lol

**Comment by NekoFoox** [comment]
Agreed. Paheal holds more images, Say.. Omori, for example. It'd greatly help to have this, or a similar program, work for saving the URLs.
