### ISSUE TITLE
after downloading it crashes...

### ISSUE THREAD

**Issue by technomooney** [LordOfPolls/Rule34-Downloader#13]
i am running on linux so i changed the cls to clear (the clear screen command for linux....) to be specific i am running KUbuntu 20.04 LTS

i get a `AttributeError: module 'os' has no attribute 'startfile'`
at the end of the running of the program...
full "crash" trace:

```python
Traceback (most recent call last):
  File "r34downloader.py", line 205, in <module>
    main.menu()
  File "r34downloader.py", line 193, in menu
    self.download(images)
  File "r34downloader.py", line 146, in download
    os.startfile(self.downloadLocation)
AttributeError: module 'os' has no attribute 'startfile'
```

i even installed the api wrapper from the github and it didn't help.

i assume it is trying to open a "menu" of some sorts... it works fine other than that....

**Comment by LordOfPolls** [comment]
#14 

Yeah i primarily program on windows, in retrospect I never really considered cross-platform when making this. Ill push a change later to support non-windows systems. For context, ``startfile`` is trying to open the directory of the downloaded files. Issue is that the devs of the os module didn't make ``startfile`` platform agnostic, it seems
