### ISSUE TITLE
Maybe make it Cross platform compatible... 

### ISSUE THREAD

**Issue by technomooney** [LordOfPolls/Rule34-Downloader#14]
considering i had to change the clear screen command to work with linux i was thinking that you primarily work on windows.... i am wondering about what else may be needing a change.... just an idea 

other then that its awesome! :stuck_out_tongue:  

i can help with setting it up to be able to run on POSTX devices (unix, linux and mac) if you want. i am still kinda a noob at python. i do know how to code in python but i just haven't worked with classes yet... and i don't know all the nifty tricks that python has...

**Comment by LordOfPolls** [comment]
Please don't create more issues to add on to previous posts. Makes it more annoying to track what's going on. I'll close this issue and reply to your original thread
