### ISSUE TITLE
Sort downloaded images from newest to oldest ?

### ISSUE THREAD

**Issue by azeman** [LordOfPolls/Rule34-Downloader#15]
So, as you know, an artist's art style can improve through the years (sometimes through the months). There are also stories that are released in several posts instead of one.

These two things mean that sometimes, we have to look at several images in chronological order (the date when it was uploaded). The problem is, since this program names downloaded images in a weird way, all of the images are scattered, making it impossible to do so...

So I suggest making it so that images are downloaded and shown in chronological order. Each post has its own "id" (a sequence of numbers such as 3993241), so perhaps this can be used somehow ?

**Comment by LordOfPolls** [comment]
Yeah i can fairly easily make that change. Right now, as this script was meant as an example for my api wrapper, it uses the filenames that Rule34 generates, rather than IDs

**Comment by azeman** [comment]
Ah great, thanks for the fast answer !
