### ISSUE TITLE
2 issues and a suggestion.

### ISSUE THREAD

**Issue by zanderjay** [LordOfPolls/Rule34-Downloader#18]
1) Tharja in specific breaks the app. Chihiro ,Diasy ,Link ,Ibuki , and Bernadette It closes after the 3 questions and then it saids 
`traceback (most recent call last):
File "main.py", line 226 in <module>
File "main.py", line 205 in menu
File "Rule34\rule34.py", line 270, in getImages
File "asyncio\base_events.py", line 616, in run_until_complete
File "Rule34\rule34.py", line 192, in getImages
File "Rule34\objectClasses.py", line 44 in parse
TypeError: string must be intergers
[12112] Failed to execute script main`
for a split second then closes.

2) I get a handful of 403 forbidden errors when downloading. Dont know if its a private image or a connection issue with that one photo. its saids
`Skipped 3542120 due to HTTP Error 403: Forbidden`
but the number changes

And I think it would be nice to limit the download by time. (Like give me all photos uploaded 07/12/2019 or newer for example)

**Comment by LordOfPolls** [comment]
1- Can I have the specific search you used, that caused the error? Without it, I can't easily replicate the issue

2- That's normal, it's a rule34 side thing. Basically for whatever reason you're not allowed to view that particular post, so by extension this program cant

Feature - Unfortunately, rule34.xxx is INCREDIBLY limited when it comes to API access. I've been considering moving to another rule34 site to allow me to offer more features. For now at least I can't implement this 

In future please can you make separate issues for each bug and feature? Means I can close each issue as each one is resolved. For example, I would close the issue with the suggestion, as it can't be done, but as you have 2 other issues that aren't resolved, I can't.

**Comment by zanderjay** [comment]
> 1- Can I have the specific search you used, that caused the error? Without it, I can't easily replicate the issue
> 
> 2- That's normal, it's a rule34 side thing. Basically for whatever reason you're not allowed to view that particular post, so by extension this program cant
> 
> Feature - Unfortunately, rule34.xxx is INCREDIBLY limited when it comes to API access. I've been considering moving to another rule34 site to allow me to offer more features. For now at least I can't implement this
> 
> In future please can you make separate issues for each bug and feature? Means I can close each issue as each one is resolved. For example, I would close the issue with the suggestion, as it can't be done, but as you have 2 other issues that aren't resolved, I can't.

Thanks for the reply! The search was simply Tharja. Those other characters worked. So that search that breaks is `Tharja` And the ones the work are `Fujisaki_Chihiro , Princess_Daisy , Link Yaoi , Mioda_Ibuki, Bernadetta_Von_Varley `

Dont know why Tharja alone kills the app and all the other characters work.

**Comment by LordOfPolls** [comment]
This should be resolved as per the V2 release
