### ISSUE TITLE
Error when trying to download something with 1 result.

### ISSUE THREAD

**Issue by TheEndri99** [LordOfPolls/Rule34-Downloader#21]
I found another bug; this time it happens only when your search has only one result.
You can replicate it searching something with 1 result, for example: venelana_gremory video.
![bug](https://user-images.githubusercontent.com/78209281/107759300-6543e580-6d28-11eb-82b9-46622c5faf59.png)

**Comment by LordOfPolls** [comment]
Thats a bug with rule34 API wrapper. Ill fix it when i get time

**Comment by TheEndri99** [comment]
Oh, I see. Of course, take your time.
