### ISSUE TITLE
PLEASE

### ISSUE THREAD

**Issue by Micolashh** [LordOfPolls/Rule34-Downloader#23]
can you add an option for using rule34.paheal.net as a source, it's way way better!

**Comment by LordOfPolls** [comment]
This was requested a while ago, i looked into `rule34.paheal.net/` and it had less images so i chose not to work on adding it

**Comment by Micolashh** [comment]
aaaaaaaaaaaaahhhhhhhhhh paheal has quality!! 
Ill learn to code and make it myself!

**Comment by LordOfPolls** [comment]
Ok
