### ISSUE TITLE
Rule34 paheal

### ISSUE THREAD

**Issue by DoomMasterted** [LordOfPolls/Rule34-Downloader#27]
could you add rule 34 paheal (the main website) to download images from?

**Comment by LordOfPolls** [comment]
This has been brought up multiple times
#23 #10 #5 

After looking into it, `paheal` has fewer images than `xxx` so I chose not to implement support for it. You're welcome to fork this apps API wrapper to add support for it, however I have no plans to add it myself

https://github.com/LordOfPolls/Rule34-API-Wrapper
