### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ghost** [LordOfPolls/Rule34-Downloader#4]
.

**Comment by LordOfPolls** [comment]
Do you mean https://rule34.paheal.net? When i was choosing which rule34 to pull from, i found it had the smallest image repository

**Comment by Acc12345** [comment]
> Do you mean https://rule34.paheal.net? When i was choosing which rule34 to pull from, i found it had the smallest image repository

Yeah. And it has the largest, actually. There is no functional downloader for it now, all existing ones are outdated and cannot download tags with large amounts of files.

**Comment by LordOfPolls** [comment]
I stand corrected then. Ill have to look into it
