### ISSUE TITLE
Program only downloads a file named https

### ISSUE THREAD

**Issue by NoToastForTheOrphans** [LordOfPolls/Rule34-Downloader#4]

**Comment by Link5261** [comment]
Ditto the info the others have stated: no actual downloads where specified, just a `https` file with no contents.
![untitled](https://user-images.githubusercontent.com/43685379/52315955-4c5d0880-2987-11e9-9f93-10a133889690.png)

**Comment by JustPoko** [comment]
I'm also having this problem. Really hoping this is fixed since the only other r34 downloader still uses the old site and doesn't accept mulitple tags.

**Comment by LordOfPolls** [comment]
Apologies, completely forgot to patch that. Ill try and have it fixed ASAP

**Comment by LordOfPolls** [comment]
Fixed as of version [2.2](https://github.com/LordOfPolls/Rule34-Downloader/releases/tag/2.2)

**Comment by Link5261** [comment]
It's in the process still, but doesn't seem to be progressing other than the command prompt bar's 'progress'. In the background of the image attached is the directory I specified for the download, and yes, I am using version 2.2.
![1](https://user-images.githubusercontent.com/43685379/52909592-2a9e3400-3259-11e9-8313-80cd1a5429b1.png)

**Comment by Link5261** [comment]
And the result: same thing as last time. Nothing but an empty "https" file created, and seemingly nothing downloaded.
![2](https://user-images.githubusercontent.com/43685379/52914305-c600ca80-3294-11e9-9c65-cf8a62104c9c.png)

**Comment by LordOfPolls** [comment]
As ive said in issue #5, im unsure whats causing the issue on some peoples computers. I havent been able to replicate the issue on any of my computers/VMs/Windows Sandbox

**Comment by petrolivro** [comment]
same for me
