### ISSUE TITLE
Can you add another rule34 site domain?

### ISSUE THREAD

**Issue by saxking892** [LordOfPolls/Rule34-Downloader#5]
Hi LordOfPolls I'm using it really well.

But Can you add another rule34 site domain?

For example 
https://rule34.paheal.net
https://rule34hentai.net

Because There are more data than What are supporting here 
(I think you use domain https://rule34.xxx/)

I am not good at english so i am sorry 

But i think you can understand what i am saying

Thankyou very much God Bless you

**Comment by LordOfPolls** [comment]
Hi, im working on that now. Ive had another request for the same addition. 

And yes, im using rule34.xxx
