### ISSUE TITLE
App creating a new folder named with the tags, too much tags it crashes

### ISSUE THREAD

**Issue by trashIntegral** [LordOfPolls/Rule34-Downloader#7]
I use broad tags then trim it down using a dash to negate other tags. It then says the number of found images, i confirm i want to download, confirm videos it loads and then crashes with an error message i cant read because its too fast.
I can only guess its due to the use of too much characters in the folder name.
I'd recommend making it so that the folder you choose to download in is the place where the files go instead of creating a new one.

**Comment by LordOfPolls** [comment]
Yep, sounds like youre hitting the path length limit which is about 260 characters if memory serves. You can override that, but thats obviously not ideal. 
Ill update the script accordingly to fix the issue

**Comment by LorenzoMattiussi** [comment]
If you want download images with a lot of tags you can temporarily edit folder name by removing the part where it add at the folder name the tags, you can easily name the folder as you want without the tags until you wait for the new version of the script

**Comment by LorenzoMattiussi** [comment]
> I use broad tags then trim it down using a dash to negate other tags. It then says the number of found images, i confirm i want to download, confirm videos it loads and then crashes with an error message i cant read because its too fast.
> I can only guess its due to the use of too much characters in the folder name.
> I'd recommend making it so that the folder you choose to download in is the place where the files go instead of creating a new one.

If you want download images with a lot of tags you can temporarily edit folder name by removing the part where it add at the folder name the tags, you can easily name the folder as you want without the tags until you wait for the new version of the script

**Comment by LordOfPolls** [comment]
You can also disable the path limit using the python installer, which is also probably why i never saw the bug during testing. 

Anyways, update expected in the next day or so

**Comment by LordOfPolls** [comment]
Fixed in latest commit: 6bdfc20e81a1cea857cf3de5bb660c26e6896bd6
