### ISSUE TITLE
Parallel downloads

### ISSUE THREAD

**Issue by LorenzoMattiussi** [LordOfPolls/Rule34-Downloader#8]
Hi is possible to download multiple images like 5 or 10 at the same time or only 1 by one?
Ps. Thanks for the script is fantastic

**Comment by LordOfPolls** [comment]
Sure. I would point out however, that there is diminishing overall speed the more simultaneous download streams that you start, so ill likely cap it to one download per core (aka a quad core will download 4 images at once)

**Comment by LorenzoMattiussi** [comment]
> Sure. I would point out however, that there is diminishing overall speed the more simultaneous download streams that you start, so ill likely cap it to one download per core (aka a quad core will download 4 images at once)

Ok and how can I do that?
